### ISSUE TITLE
Connection to storage adapter is refused.

### ISSUE THREAD

**Issue by giyeh** [Azure/azure-iot-pcs-remote-monitoring-java#37]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Run docker-compose up, and see how storageadapter_1 crashes with the following error:

config_1            | [error] c.m.a.i.u.s.h.HttpClient - Request failed
config_1            | org.apache.http.conn.HttpHostConnectException: Connect to storageadapter:9022 [storageadapter/172.19.0.2] failed: Connection refused (Connection refused)
config_1            | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
config_1            | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
config_1            | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
config_1            | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
config_1            | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
config_1            | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
config_1            | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
config_1            | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
config_1            | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
config_1            | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
config_1            | Caused by: java.net.ConnectException: Connection refused (Connection refused)
config_1            | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
config_1            | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
config_1            | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
config_1            | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
config_1            | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
config_1            | 	at java.net.Socket.connect(Socket.java:589)
config_1            | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
config_1            | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
config_1            | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
config_1            | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)

# Steps to reproduce
Run docker-compose up, see the error.

# Expected behavior
Shouldn't crash.

# Current behavior
Crashes right now at load.

# Known workarounds
Eventually works, but not sure why it's hitting this.

**Comment by giyeh** [comment]
Here are the logs.

[Error_logs_docker_compose_up.txt](https://github.com/Azure/azure-iot-pcs-remote-monitoring-java/files/1613198/Error_logs_docker_compose_up.txt)
